### ISSUE TITLE
App研发录第一章：重构夜未眠

### ISSUE THREAD

**Issue by qmsggg** [qmsggg/BlogCollect#36]
- 重新规划Android项目结构
公共库和业务逻辑分包存放
- 为Activity定义新的生命周期
重写比如onCreate方法中的各个逻辑
可以拆分为initVariables,initViews(Bundle s),loadData等方法
- 统一事件编程模型
尽量少用R.id 增加else if 判断 并且影响面向对象编程，在onclick方法中调用事件相应方法
- 页面跳转尽量使用实体类
要记得序列化

**Comment by qmsggg** [comment]
# 自动登陆
本地保存密码和用户名？？？？
每次接口请求都带上？？？？

很明显是不得行的。

### 采用Cookie

**Comment by qmsggg** [comment]
# NegativeArraySizeException
声明数组为-1

String[] arg1 = new String[args.length - 1]
args.length = 0;

**Comment by qmsggg** [comment]
# ConcurrentModificationException
1.遍历集合的同时又在删除集合当中的元素
2.多线程同时操作同一个集合，可以换成线程安全集合

**Comment by qmsggg** [comment]
# 不能随便使用asList
```
at java.util.AbstractList.remove(AbstractList.java:161)
	at java.util.AbstractList$Itr.remove(AbstractList.java:374)
	at java.util.AbstractCollection.remove(AbstractCollection.java:293)
	at hank.luohao.test.Main.main(Main.java:12)
```
导致错误代码：
```
public class Main {
	public static void main(String[] args) {
		String str = "1,2,3,4,5";
		List<String> test = Arrays.asList(str.split(","));
		test.remove("1");
	}
}
```

Arrays.asList()的返回值类型为java.util.Array$ArrayList，而不是ArrayList

**Comment by qmsggg** [comment]
# ClassNotFoundException
动态加载类找不到

**Comment by qmsggg** [comment]
# NoClassDefFoundError
当我们在B类中声明了一个A类的实例，如下：
```
ClassA obj = new ClassA();
```
但是打包时B和A分别位于不同的DEX中，这时如果A所在的DEX中把A类删除了，那么就会抛出此异常。
通常在插件化编程的时候会遇到这类问题，因为要使用到DexClassLoader

**Comment by qmsggg** [comment]
# Unable to start receiver
不能启动BroadcastReceiver等
在Activity之外调用startActivity的时候，要调用
```
intent.addFlage(Intent.FLAG_ACTIVITY_NEW_TASK);
```

**Comment by qmsggg** [comment]
# View not attached to window manager
发生这类Exception的场景是，又一个费时的线程任务，在任务开始的时候显示一个对话框，然后当任务完成了再销毁对话框，在此期间如果Activity因为某种原因被杀掉且又重新启动了，那么当Dialog调用dismiss方法的时候WindowManager检查发现Dialog所属的Activity已经不复存在了。
需要注意以下：
1）正确使用对话框，不要在非UI线程中使用对话框创建，显示和取消对话框，
2）一定要让对话框对象在Activity的可控范围之内和声明周期之内。比如对话框一定要是Activity的成员变量，并且在让对话框变量活跃在Activity的onCreate（）和onDestroy（）这两个方法之间。
一个引发Crash的列子：
```
private ProgressDialog mProgressDialog;

@Override
public void onCreate(Bundle savedInstanceState) {
	...
	mProgressDialog = new ProgressDialog(this);
	mProgressDialog.show();

	new Handler().postDelayed(new Runnable() {
		@Override
		public void run() {
		    mProgressDialog.dismisss();
		}
	}, 1000);
	finish();
}
```

一个完美的解决方案：
重写Dialog的dismiss方法，判断context所属的activity.isFinishing();
